# Generated by Django 5.1.15 on 2026-06-12 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=128, verbose_name='密码（hash）')),
                ('admin_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='登录令牌')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '管理员',
                'db_table': 'b_admin',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='跳转链接')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '广告',
                'db_table': 'b_banner',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='分类名')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '分类',
                'db_table': 'b_classification',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='公司名')),
                ('logo', models.CharField(blank=True, max_length=255, null=True, verbose_name='logo')),
                ('scale', models.CharField(blank=True, max_length=32, null=True, verbose_name='规模')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('description', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '公司',
                'db_table': 'b_company',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '公告',
                'db_table': 'b_notice',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='OpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='IP')),
                ('re_time', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
                ('re_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='请求地址')),
                ('re_method', models.CharField(blank=True, max_length=16, null=True, verbose_name='方法')),
                ('re_content', models.CharField(blank=True, max_length=255, null=True, verbose_name='说明')),
                ('access_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='耗时(ms)')),
            ],
            options={
                'verbose_name': '操作日志',
                'db_table': 'b_op_log',
                'ordering': ['-re_time'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签',
                'db_table': 'b_tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='账号/工号/邮箱')),
                ('password', models.CharField(max_length=128, verbose_name='密码（hash）')),
                ('nickname', models.CharField(blank=True, max_length=64, null=True, verbose_name='昵称')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='邮箱')),
                ('gender', models.CharField(blank=True, max_length=8, null=True, verbose_name='性别')),
                ('description', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('role', models.CharField(choices=[('user', '求职者'), ('hr', '招聘方')], default='user', max_length=16, verbose_name='角色')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '封禁')], default='0', max_length=2, verbose_name='状态')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='登录令牌')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户',
                'db_table': 'b_user',
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='岗位名')),
                ('cover', models.CharField(blank=True, max_length=255, null=True, verbose_name='封面')),
                ('description', models.TextField(blank=True, null=True, verbose_name='岗位描述')),
                ('salary', models.CharField(blank=True, max_length=32, null=True, verbose_name='薪资')),
                ('status', models.CharField(choices=[('1', '上架'), ('2', '下架')], default='1', max_length=2, verbose_name='状态')),
                ('browse_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('wish_count', models.IntegerField(default=0, verbose_name='想去人数')),
                ('collect_count', models.IntegerField(default=0, verbose_name='收藏量')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.classification')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.company')),
                ('tags', models.ManyToManyField(blank=True, to='myapp.tag')),
                ('collect_users', models.ManyToManyField(blank=True, related_name='collect_things', to='myapp.user')),
                ('wish_users', models.ManyToManyField(blank=True, related_name='wish_things', to='myapp.user')),
            ],
            options={
                'verbose_name': '岗位',
                'db_table': 'b_thing',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('education', models.CharField(blank=True, max_length=32, null=True, verbose_name='学历')),
                ('experience', models.CharField(blank=True, max_length=32, null=True, verbose_name='工作年限')),
                ('content', models.TextField(blank=True, null=True, verbose_name='简历内容')),
                ('file', models.CharField(blank=True, max_length=255, null=True, verbose_name='附件')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '简历',
                'db_table': 'b_resume',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='编号')),
                ('status', models.CharField(default='1', max_length=2, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('thing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.thing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'verbose_name': '投递',
                'db_table': 'b_order',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.user', verbose_name='所属用户'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('like_count', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.thing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'verbose_name': '评论',
                'db_table': 'b_comment',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='联系人')),
                ('mobile', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=255, verbose_name='详细地址')),
                ('is_default', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'verbose_name': '地址',
                'db_table': 'b_address',
            },
        ),
    ]
